# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demo
  pod 'MobileCenter/Crashes', '~> 0.13.0'
  pod 'MobileCenter/Analytics', '~> 0.13.0'
  pod 'RNMobileCenterShared', '~> 0.10.0'

  

  target 'demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'demo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demo-tvOS

  target 'demo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
